apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: helmrelease-example
  namespace: flux-system
spec:
  targetNamespace: dev
  interval: 5m
  chart:
    spec:
      chart: podinfo
      version: "5.0.0"
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: management
      interval: 1m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  test:
    enable: false
  values:
    image:
      repository: ghcr.io/stefanprodan/podinfo # {"$imagepolicy": "flux-system:podinfo:name"}​
      tag: 5.0.0 # {"$imagepolicy": "flux-system:podinfo:tag"}​
    service:
      grpcService: backend
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
