apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: image-policy-example
  namespace: flux-system
spec:
  interval: 5m0s
  path: ../../image-update-automation/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
  targetNamespace: flux-system
  suspend: false