apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: backend
  namespace: management-namespace
spec:
  releaseName: backend
  serviceAccountName: flux-reconciler
  targetNamespace: default
  interval: 5m
  chart:
    spec:
      chart: podinfo
      version: "5.0.0" # {"$imagepolicy": "cluster-1-flux-system:podinfo:tag"}
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: default
      interval: 1m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  test:
    enable: false
  values:
    image:
      repository: ghcr.io/stefanprodan/podinfo # {"$imagepolicy": "cluster-1-flux-system:podinfo:name"}
      tag: 6.2.3 # {"$imagepolicy": "cluster-1-flux-system:podinfo:tag"}
    service:
      grpcService: backend
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
