apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: on-call-webapp
  namespace: flux-system
spec:
  summary: "production cluster"
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
    - kind: Helmepository
      name: '*'
      namespace: '*'
    - kind: GitRepository
      name: '*'
      namespace: '*'
    - kind: Kustomization
      name: '*'
      namespace: '*'