apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: autoupdate-example
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: podinfo
      version: "5.0.0"
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: default
      interval: 1m
  dependsOn:
    - name: backend
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  test:
    enable: false
