apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: backend
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: podinfo
      version: "5.0.0" # {"$imagesdadapolicy": "cluster-1-flux-system:podinfo:tag"}
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: default  
      interval: 1m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  test:
    enable: false
  values:
    image:
      repository: ghcr.io/stefanprodan/podinfo # {"$imagepolicy": "cluster-1-flux-system:podinfo:name"}
      tag: 5.0.0  # {"$imagepolicy": "cluster-1-flux-system:podinfo:tag"}
    service:
      grpcService: backend
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frontend
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: podinfo
      version: "=5.0.0" 
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: default
      interval: 1m
  dependsOn:
    - name: backend
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  test:
    enable: false
  values:
    backend: http://backend-podinfo:9898/echo
    resources:
      requests:
        cpu: 100m
        memory: 64Mi